sudo: false
language: go
go:
    - 1.4
services:
    - docker
addons:
    apt:
        packages:
        - protobuf-compiler
        - cmake
        - libgeoip-dev
        - debhelper
install:
    - . build.sh
script:
    - make test
    - make deb
    - mkdir /tmp/heka && find . -name "*.deb" -exec cp {} /tmp/heka/heka.deb \;
    - cp ../docker/Dockerfile.travis /tmp/heka/Dockerfile
    - docker build -t xrlx/heka:$TRAVIS_BRANCH /tmp/heka
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push xrlx/heka
