sudo: false
language: go
go:
    - 1.6
services:
    - docker
addons:
    apt:
        packages:
        - protobuf-compiler
        - cmake
        - libgeoip-dev
        - debhelper
install:
    - . build.sh
script:
    - make test
    - cd ../docker && sh build_docker.sh
